#!/bin/bash
BASEDIR="$(dirname "$0")"/..
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo -e "\nValidating Javascript:\n"

# Check for eslint
eslint="$BASEDIR/node_modules/.bin/eslint"
which "$eslint" &>/dev/null
if [[ "$?" == 1 ]]; then
  echo -e "\e[31mPlease install ESlint\e[0m"
  exit 1
fi

for FILE in $STAGED_FILES; do
  "$eslint" "$FILE"

  if [[ "$?" == 0 ]]; then
    echo -e "\e[31mESLint Passed: $FILE\e[0m"
  else
    echo -e "\e[31mESLint Failed: $FILE\e[0m"
    PASS=false
  fi
done

echo -e "\nJavascript validation completed!\n"

if ! $PASS; then
  echo -e "\033COMMIT FAILED:\e[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
  exit 1
else
  echo -e "\033COMMIT SUCCEEDED\e[0m\n"
fi

exit $?
